# Generated by Django 4.2.14 on 2024-08-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(choices=[('Yes', 'Yes'), ('NO', 'NO')], default=None),
        ),
    ]
